version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.local
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.local
    ports:
      - "80:3000"
  redis:
    image: redis