version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.local
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.local
    ports:
      - "3000:3000"
  redis:
    image: redis