version: '3'
services:
  api:
    environment:
      - MONGODB_USER=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=database:27017
      - MONGODB_NAME=local_db
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=local_db