version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"