version: '3'
services:
  api:
    networks:
      - internal
    depends_on:
      - redis
  frontend:
    networks:
      - internal
    depends_on:
      - api
    environment:
      - API_URL=http://api:3000
  redis:
    networks:
      - internal
    restart: unless-stopped
    image: redis
networks:
  internal:
    driver: bridge