version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - MONGODB_USER=MyUsername
      - MONGODB_PASSWORD=MyPassword
      - MONGODB_HOST=MyDatabaseHost:27017
      - MONGODB_NAME=MyDatabase
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"